### PR TITLE
Add Version to GA

### PR DESCRIPTION
**Pull request by JnSnw**

### CODE REVIEW

**Comment by JnSnw** [comment]
> I am a little confused: We do that for Analytics? To provide a version number in the logs?

Sorry, missed to commit the other changes.
I added some events to the services, so we are able to track the usage of the services.
Maybe we can also add some events to the called methods.

**Comment by christianaschoff** [comment]
> > I am a little confused: We do that for Analytics? To provide a version number in the logs?
> 
> Sorry, missed to commit the other changes.
> I added some events to the services, so we are able to track the usage of the services.
> Maybe we can also add some events to the called methods.

:)

I am no expert on that, but wouldn't log-events more insightful if we raise certain events on user interactions instead of when the class is instantiated?
I am not sure if we would gain helpful insights just by placing that in the constructor on its own.

Please correct me if I am wrong :)

**Comment by JnSnw** [comment]
> > > I am a little confused: We do that for Analytics? To provide a version number in the logs?
> > 
> > 
> > Sorry, missed to commit the other changes.
> > I added some events to the services, so we are able to track the usage of the services.
> > Maybe we can also add some events to the called methods.
> 
> :)
> 
> I am no expert on that, but wouldn't log-events more insightful if we raise certain events on user interactions instead of when the class is instantiated?
> I am not sure if we would gain helpful insights just by placing that in the constructor on its own.
> 
> Please correct me if I am wrong :)

Hi Christian,

you are right. I'm not familiar with angular. Will the constructor called if the page is loaded initially or if the customer calls the service?
I wanted to add the events to the method calls itself, but right now, I dont know to which methods and I don't want to add unnecessary events.

Could we have a session to discuss which events we actually need?

**Comment by christianaschoff** [comment]
> > > > I am a little confused: We do that for Analytics? To provide a version number in the logs?
> > > 
> > > 
> > > Sorry, missed to commit the other changes.
> > > I added some events to the services, so we are able to track the usage of the services.
> > > Maybe we can also add some events to the called methods.
> > 
> > 
> > :)
> > I am no expert on that, but wouldn't log-events more insightful if we raise certain events on user interactions instead of when the class is instantiated?
> > I am not sure if we would gain helpful insights just by placing that in the constructor on its own.
> > Please correct me if I am wrong :)
> 
> Hi Christian,
> 
> you are right. I'm not familiar with angular. Will the constructor called if the page is loaded initially or if the customer calls the service?
> I wanted to add the events to the method calls itself, but right now, I dont know to which methods and I don't want to add unnecessary events.
> 
> Could we have a session to discuss which events we actually need?

Absolutely :). Would love to have a session to go through the app and place some ga insights events with you. Lets do that this weekend. Before that I will not have the time for that.
If someone else would like to do it with you instead, I would be fine with that as well :)

**Pull request merged**
