### PR TITLE
improvement: readded the changes out of PRs #38, #44 and #41 to the redesign branch

### PR DESCRIPTION
**Pull request by mfranzke**

### CODE REVIEW

**Comment by patsimm** [comment]
Ok - the redesign branch is now already in the incubator (default) branch. I changed the target branch therefore. Is it possible for you to resolve the conflicts? I already added the alt tags so there is some conflicts for that part and some other too. Else I will look into that later.

**Comment by mfranzke** [comment]
@patsimm, done.

**Comment by patsimm** [comment]
Just merged it but I think we have to look into this again. The image looks a little blurry on smaller phones. It's probably because it has `object-fit: cover` and scales its height to `70vh`. The size of the images should therefore be depending on the screen-height - not the screen width.

**Comment by patsimm** [comment]
I fixed that issue in https://github.com/LokalKauf/lokalkauf-frontend/commit/cd120bd154670b53de45f5e7c1004db61f62f08d

**Pull request merged**
