### PR TITLE
update readme and provide instructions for running firebase emulators

### PR DESCRIPTION
**Pull request by patsimm**
@buecheko @JnSnw I got the firebase emulators running locally on my machine. I added some instructions to the `README.md`. Could you test if that works for you?

### CODE REVIEW

**Comment by JnSnw** [comment]
@patsimm solleten wir das nicht lieber in das functions repo packen?

**Comment by patsimm** [comment]
I think it won't be easy to run the functions locally without emulating the hosting part. How are you testing if your function works right now? I think we should rather get the functions back in this repository so we have everything together here which makes it easier to run the functions locally connected to the frontend running locally.

**Comment by JnSnw** [comment]
I'm actually against moving everything into a repo. If the application gets bigger, that's gonna be a problem eventually.
The current development of software has shown that.
People no longer build monolytes, but rather microservices. We should stick to that as well.

Currently I host the app locally and deploy the function on firebase to test it. But with your method I could run both locally.

**Comment by patsimm** [comment]
Having a microservice architecture doesn't mean you can't put everything into one repo. I'm not saying it is always a good idea to do that but I think it's the firebase way to do it. Monorepos are a in my point of view a very valid thing to do that has proven to work in lots of cases. I am not really seeing a problem right now putting the two repos together. How I see it, right now it would just make things easier and less complex (e.g. starting emulators locally, deploying everything at once) if we have it all together in the single repo. That's also how the firebase tooling actually is expecting it to be. 

To get back to the PR here and the emulators... To run the functions locally and have the frontend connected to the locally running functions you will need to start the frontend in the emulator also. That means it's not enough to just run `ng serve` or `npm run start` to start the frontend locally anymore. You will need to build the frontend `npm run build` and have the built files in the`dist`-directory. Then when running the hosting-emulator it serves the built app from there. The functions-emulator will serve the functions in the `functions`-directory.  Where the functions and the dist folder can be found is configured in the `firebase.json` file. Those two emulators are then connected together by firebase tooling so the frontend will call the locally hosted functions.  I am not sure how easily this all is managable when we have two different repositories with two different 'firebase.json' files.

**Comment by patsimm** [comment]
@JnSnw but even if we don't put everything into one repo. Would it be a problem to merge this MR?

**Comment by JnSnw** [comment]
@patsimm sorry, totally forgot to merge it. Will merge it now.

**Pull request merged**
