### PR TITLE
improvement(bgimg): optimized image size

### PR DESCRIPTION
**Pull request by mfranzke**
Performance optimization by reducing the main and initial background image size by several image compression and optimization tools down to 10% and less of its original size and switched to JPEG which provides better image compression feasibility.

### CODE REVIEW

**Comment by patsimm** [comment]
Thanks a lot for that PR! This is something we have already thought of doing. We're right now in a redesigning process and the background image will change also. Can you point as to a tool that you are using for generating the different image sizes and doing the compressions?

**Comment by mfranzke** [comment]
sure:
- https://www.jpegmini.com/ (commercial) and
- https://imageoptim.com/

If I could still support you regarding the next release or doing those image compressions again, feel free to reach out to me again (especially because of the costs of the JPEGMini software).

**Comment by patsimm** [comment]
Sure, if you have a look at our redesign branch (#37) you could do the same that you did in this PR there? The hero image we are using there is slightly the same but a little bigger.

**Comment by mfranzke** [comment]
sure, I could do that.

As you've changed to a responsive layout with a full width hero image, I would additionally like to suggest to use breakpoints for some common viewport formats to shrink the image sizes specifically for them even further. I'll provide both the SCSS and image for those later.

**Comment by mfranzke** [comment]
@patsimm, I've included some checkin with PR #45

**Pull request closed without merging**
